# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ceca21fca2fd10768618ef66902072b1cdb2a582861a9656c93ce5a8d5d5ee9c75858acb303407b837b91b8973a8ba009c5f5064f59de49e2ad1d267cbe2525

test:
  secret_key_base: 00cd89fb9f773c85dcc87a70b4c16e6964886f0146d0f9896ab13bc2a33b1e49e1a30da35af6d5134ca151940490c7bc23fd46692e0f345806958aa0a664645b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
